# num1 = int(input("enter first: "))
# num2 = int(input("enter second: "))

# num1 = num1 ^ num2
# num2 = num1 ^ num2
# num1 = num1 ^ num2

# print("after swapping the first nunmber is: ", num1)
# print("after swapping the second number is: ", num2)
a = 12
b = 15

temp = a
a = b
b = temp
print("after swapping the first number is: ", a)
print("after swapping the second number is: ",b)

x = 34
y = 21

x, y = y, x
print("after swapping the first number is: ", x)
print("after swapping the first number is: ", y)